google.load('visualization', '1', {'packages': ['geomap']});
   google.setOnLoadCallback(drawMap);

function drawMap() {
var data = google.visualization.arrayToDataTable([
	['Country', 'Users'],
		['US', 2476],
		['GB', 406],
		['CA', 242],
		['DE', 227],
		['BR', 167],
		['AU', 154],
		['FR', 101],
		['SE', 87],
		['JP', 75],
		['ES', 74],
		['NL', 65],
		['PL', 56],
		['DK', 54],
		['CN', 54],
		['NO', 53],
		['RU', 51],
		['IN', 50],
		['CH', 45],
		['IT', 40],
		['AT', 38],
		['FI', 36],
		['PT', 29],
		['BE', 28],
		['NZ', 27],
		['AR', 27],
		['IE', 23],
		['MX', 22],
		['PH', 21],
		['ZA', 19],
		['SG', 19],
		['UA', 15],
		['RO', 14],
		['HU', 14],
		['CO', 14],
		['CZ', 13],
		['TW', 11],
		['IL', 11],
		['TR', 8],
		['LT', 8],
		['MY', 7],
		['IS', 7],
		['SI', 6],
		['UY', 5],
		['TH', 5],
		['HR', 5],
		['EE', 5],
		['CV', 5],
		['CL', 5],
		['BG', 5],
		['VN', 4],
		['RS', 4],
		['LV', 4],
		['KR', 4],
		['GR', 4],
		['VE', 3],
		['SK', 3],
		['MK', 3],
		['JO', 3],
		['HK', 3],
		['EG', 3],
		['EC', 3],
		['BY', 3],
		['BO', 3],
		['PK', 2],
		['PE', 2],
		['LU', 2],
		['LK', 2],
		['ID', 2],
		['BD', 2],
		['YE', 1],
		['VI', 1],
		['TN', 1],
		['SC', 1],
		['SA', 1],
		['PY', 1],
		['PS', 1],
		['PF', 1],
		['NI', 1],
		['NG', 1],
		['NC', 1],
		['MW', 1],
		['MT', 1],
		['MD', 1],
		['KY', 1],
		['KW', 1],
		['IR', 1],
		['GY', 1],
		['GE', 1],
		['GD', 1],
		['ET', 1],
		['DO', 1],
		['CU', 1],
		['CR', 1],
		['BM', 1],
	]);
	var options = {};
options['dataMode'] = 'regions';
options['width'] = '1000px';
options['height'] = '600px';
var container = document.getElementById('map_canvas_regions');
      var geomap = new google.visualization.GeoMap(container);
      geomap.draw(data, options);
};